---
version: "3.5"
services:
  harmony-collector:
    image: harmony-collector
    container_name: harmony-collector-0
    restart: always
    environment:
      API_KEY: $API_KEY
      X_CONTENT_TYPE_OPTIONS: $X_CONTENT_TYPE_OPTIONS
      ACCESS_CONTROL_ALLOW_ORIGIN: $ACCESS_CONTROL_ALLOW_ORIGIN
      ACCESS_CONTROL_ALLOW_HEADERS: $ACCESS_CONTROL_ALLOW_HEADERS
    ports:
      - 8080:5000
networks:
  collector-net:
    name: collector-net
    driver: bridge
